const { contextBridge, ipcRenderer } = require('electron');

const invoke = (ch) => (...a) => ipcRenderer.invoke(ch, ...a);
const on = (ch) => (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on(ch, h); return () => ipcRenderer.off(ch, h); };

contextBridge.exposeInMainWorld('lellek', {
  versions: { list: invoke('versions:list'), fabric: invoke('loaders:fabric'), forge: invoke('loaders:forge'), neoforge: invoke('loaders:neoforge') },
  profiles: { list: invoke('profiles:list'), save: invoke('profiles:save'), delete: invoke('profiles:delete'), openFolder: invoke('profiles:openFolder'), duplicate: invoke('profiles:duplicate'), export: invoke('profiles:export'), import: invoke('profiles:import'), exportMrpack: invoke('profiles:exportMrpack') },
  content: { list: invoke('content:list'), toggle: invoke('content:toggle'), remove: invoke('content:remove'), add: invoke('content:add'), openFolder: invoke('content:openFolder'), checkUpdates: invoke('mods:checkUpdates'), update: invoke('mods:update'), drop: invoke('content:drop') },
  pathOf: (file) => require('electron').webUtils.getPathForFile(file),
  auth: { login: invoke('auth:login'), logout: invoke('auth:logout'), current: invoke('auth:current'), list: invoke('auth:list'), switch: invoke('auth:switch'), remove: invoke('auth:remove'), onChange: on('auth:changed') },
  skins: { list: invoke('skins:list'), add: invoke('skins:add'), remove: invoke('skins:remove'), apply: invoke('skins:apply'), saveCurrent: invoke('skins:saveCurrent') },
  voice: { status: invoke('voice:status') },
  cosmetics: { status: invoke('cosmetics:status'), myCape: invoke('cosmetics:myCape'), uploadCape: invoke('cosmetics:uploadCape'), deleteCape: invoke('cosmetics:deleteCape') },
  logs: { openFolder: invoke('logs:openFolder'), openLast: invoke('logs:openLast') },
  worlds: { list: invoke('worlds:list'), export: invoke('worlds:export'), import: invoke('worlds:import'), delete: invoke('worlds:delete'), copy: invoke('worlds:copy'), openFolder: invoke('worlds:openFolder') },
  server: { info: invoke('server:info'), setup: invoke('server:setup'), start: invoke('server:start'), stop: invoke('server:stop'), command: invoke('server:command'), importWorld: invoke('server:importWorld'), openFolder: invoke('server:openFolder'), onLog: on('server:log'), onState: on('server:state') },
  skin: { upload: invoke('skin:upload'), setCape: invoke('cape:set'), texture: invoke('skin:texture'), of: invoke('skin:of') },
  presets: { list: invoke('presets:list'), create: invoke('presets:create') },
  browse: { search: invoke('browse:search'), install: invoke('browse:install') },
  vanilla: { info: invoke('vanilla:info'), importSettings: invoke('vanilla:importSettings'), link: invoke('vanilla:link') },
  packs: { search: invoke('packs:search'), install: invoke('packs:install') },
  bundle: { list: invoke('bundle:list'), install: invoke('bundle:install'), open: invoke('bundle:open') },
  spotify: { status: invoke('spotify:status'), login: invoke('spotify:login'), logout: invoke('spotify:logout') },
  settings: { get: invoke('settings:get'), save: invoke('settings:save'), openDataDir: invoke('settings:openDataDir') },
  launch: invoke('launch'),
  streamer: { get: invoke('streamer:get'), set: invoke('streamer:set'), onState: on('streamer:state') },
  ui: { get: invoke('ui:get'), save: invoke('ui:save'), pickBackground: invoke('ui:pickBackground'), clearBackground: invoke('ui:clearBackground'), zoom: invoke('ui:zoom') },
  pc: { check: invoke('pc:check'), setMemory: invoke('profiles:setMemory') },
  shotDiscord: invoke('shots:discord'),
  details: invoke('browse:details'), changelog: invoke('mods:changelog'),
  friends: { list: invoke('friends:list'), add: invoke('friends:add'), remove: invoke('friends:remove'), status: invoke('friends:status'), respond: invoke('friends:respond'), cancel: invoke('friends:cancel'), block: invoke('friends:block'), unblock: invoke('friends:unblock'), setStatus: invoke('friends:setStatus'), edit: invoke('friends:edit'), invite: invoke('friends:invite'), onUpdate: on('friends:update'), onInvite: on('friends:invite') },
  serverContent: { list: invoke('servercontent:list'), search: invoke('servercontent:search'), install: invoke('servercontent:install'), remove: invoke('servercontent:remove'), toggle: invoke('servercontent:toggle'), openFolder: invoke('servercontent:openFolder') },
  tunnel: { start: invoke('tunnel:start'), stop: invoke('tunnel:stop'), onState: on('tunnel:state') },
  setServerAddress: invoke('server:setAddress'),
  shortcut: invoke('shortcut:create'),
  stats: { get: invoke('stats:get'), reset: invoke('stats:reset') },
  modsets: { list: invoke('modsets:list'), save: invoke('modsets:save'), apply: invoke('modsets:apply'), remove: invoke('modsets:delete') },
  modList: invoke('mods:exportList'),
  serverProps: { get: invoke('serverprops:get'), save: invoke('serverprops:save') },
  diagnose: { last: invoke('crash:analyzeLast'), adjustMemory: invoke('profiles:adjustMemory'), clearJava: invoke('profiles:clearJava') },
  worldInfo: invoke('worlds:info'), favoritesFromServersDat: invoke('favorites:fromServersDat'), modInfo: invoke('mods:info'), packPreview: invoke('packs:preview'), backupAll: invoke('backup:all'), restoreAll: invoke('backup:restoreAll'), shotCopy: invoke('shots:copy'), profileIcon: invoke('profiles:icon'),
  update: { check: invoke('update:check'), open: invoke('update:open'), download: invoke('update:download'), install: invoke('update:install'), onProgress: on('update:progress') },
  java: { list: invoke('java:list'), delete: invoke('java:delete'), install: invoke('java:install') },
  disk: { profile: invoke('disk:profile'), clean: invoke('disk:clean') },
  imports: { scan: invoke('import:scan'), profile: invoke('import:profile') },
  autostart: invoke('autostart:set'),
  modtools: { conflicts: invoke('mods:conflicts'), safeToggle: invoke('mods:safeToggle') },
  serverPing: invoke('server:ping'),
  backups: { list: invoke('backups:list'), restore: invoke('backups:restore'), now: invoke('backups:now'), openFolder: invoke('backups:openFolder') },
  shots: { list: invoke('shots:list'), open: invoke('shots:open'), openFolder: invoke('shots:openFolder'), delete: invoke('shots:delete') },
  favorites: { list: invoke('favorites:list'), save: invoke('favorites:save') },
  crashOpen: invoke('crash:open'), onTrayLaunch: on('tray:launch'),
  launchRunning: invoke('launch:running'), launchKill: invoke('launch:kill'), launchOpenLog: invoke('launch:openLog'),
  // 2.5
  tm: { list: invoke('tm:list'), snapshot: invoke('tm:snapshot'), restore: invoke('tm:restore'), remove: invoke('tm:delete') },
  share: { create: invoke('share:create'), preview: invoke('share:preview'), import: invoke('share:import') },
  ach: { get: invoke('ach:get'), setBadge: invoke('ach:setBadge'), onUnlocked: on('ach:unlocked') },
  onRecap: on('session:recap'),
  chat: { threads: invoke('chat:threads'), thread: invoke('chat:thread'), close: invoke('chat:close'), send: invoke('chat:send'), unread: invoke('chat:unread'), clear: invoke('chat:clear'), onMessage: on('chat:message'), onUnread: on('chat:unread') },
  party: { get: invoke('party:get'), poll: invoke('social:poll'), create: invoke('party:create'), invite: invoke('party:invite'), join: invoke('party:join'), decline: invoke('party:decline'), leave: invoke('party:leave'), kick: invoke('party:kick'), promote: invoke('party:promote'), plan: invoke('party:plan'), choose: invoke('party:choose'), ready: invoke('party:ready'), launch: invoke('party:launch'), cancel: invoke('party:cancel'),
    onUpdate: on('party:update'), onInvite: on('party:invite'), onCountdown: on('party:countdown'), onLaunched: on('party:launched') },
  radar: { scan: invoke('radar:scan') },
  perf: { plan: invoke('perf:plan'), apply: invoke('perf:apply') },
  home: { summary: invoke('home:summary') },
  windows: { openAnother: invoke('window:openAnother') },
  onLog: on('launch:log'),
  onProgress: on('launch:progress'),
  onClosed: on('launch:closed'),
});
